### PR TITLE
Main docu updates

### PR DESCRIPTION
**Pull request by jordijoangimenez**
This fixes sync with the development branch

### CODE REVIEW

**Review by dsilhavy — APPROVED** [review]

**Comment by dsilhavy** [comment]
@davidjwbbc Ok for you to merge to `main` directly, or do you prefer to merge `development` to `main` without doing a release?

**Comment by davidjwbbc** [comment]
I think it's nicer for the git tree to bring the main and v1.2.x branches up to the same as development since these documentation changes are already present on that branch and the development branch is just that one documentation commit ahead of main and v1.2.x.

**Comment by jordijoangimenez** [comment]
Thank you David. Good idea so we are consistent. Let me do

**Comment by davidjwbbc** [comment]
I've done it

**Comment by davidjwbbc** [comment]
Closing without merge of this PR as the same changes have been merged from the development branch.

**Pull request closed without merging**
